version: "3.8"

services:
  rogisu:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 128M